version: '2.1'

networks:
  monitor-net:
    driver: bridge
    ipam:
      config:
        - subnet: $NET.0/24
          gateway: $NET.1

volumes:
    prometheus_data:
      driver_opts:
        type: tmpfs
        device: tmpfs
        o: noatime,size=1G
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
#    tmpfs:
#      - /prometheus:dev,exec,suid,size=1G
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      monitor-net:
        ipv4_address: $NET.90
    extra_hosts:
      - host:$NET.1
    labels:
      group: "monitoring"

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    working_dir: /etc/alertmanager
    command:
      - '--config.file=config.yml'
      - '--storage.path=/alertmanager'
#      - '--log.level=debug'
      - '--web.external-url=http://alertmanager:9093/'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      monitor-net:
        ipv4_address: $NET.93
    labels:
      group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v1.3.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      monitor-net:
        ipv4_address: $NET.100
    labels:
      group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - $DOCKER_DIR:$DOCKER_DIR:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      monitor-net:
        ipv4_address: $NET.80
    labels:
      group: "monitoring"

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

      - GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_ALERTING_ENABLED=false
      - GF_PANELS_ENABLE_ALPHA=true
      - GF_METRICS_ENABLED=true
      - GF_METRICS_INTERVAL_SECONDS=15
    restart: unless-stopped
    expose:
      - 3000
    networks:
      monitor-net:
        ipv4_address: $NET.2
    labels:
      group: "monitoring"

  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      monitor-net:
        ipv4_address: $NET.91
    labels:
      group: "monitoring"

  caddy:
    image: caddy:2.3.0
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - ./caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP}
    restart: unless-stopped
    networks:
      monitor-net:
        ipv4_address: $NET.99
    labels:
      group: "monitoring"

  blackbox:
    image: prom/blackbox-exporter:v0.19.0
    container_name: blackbox
#    ports:
#      - "9115:9115"
#    dns: 8.8.8.8
    restart: unless-stopped
    expose:
      - 9115
    networks:
      monitor-net:
        ipv4_address: $NET.115
    volumes:
      - ./blackbox:/blackbox
    command: 
      - --config.file=/blackbox/blackbox.yml
    labels:
      group: "monitoring"

